name: 'PR JIRA Action'
description: 'Creates a JIRA ticket based off of a pull request'
inputs:
  github-token:
    description: 'Usually secrets.GITHUB_TOKEN'
    required: true
  project-id:
    description: 'The id which maps to the project to create a ticket for'
    required: false
  project-name:
    description: 'The name which maps to the project to create a ticket for'
    required: false
  component:
    description:
    required: false
  assignee:
    description: 'Email linked to a JIRA account to assign the ticket to'
    required: false
  host:
    description: 'Url for the JIRA server'
    required: true
    default: jira.common.bluescape.com
  username:
    description: 'Username for authentication of the API requests'
    required: true
  password:
    description: 'Password for authentication of the API requests'
  status:
    description: 'The status to set the ticket to'
    required: false
    default: 'In Progress'
runs:
  using: 'node16'
  main: 'src/index.js'
